### ISSUE TITLE
README - separate user vs developer install instructions

### ISSUE THREAD

**Issue by ljdursi** [CanDIG/go-model-service#4]
Shorten the installation instructions a bit (don’t need to install go-swagger to compile + run, for instance) and then have a longer “for developers” section that includes dev tool requirements and instructions for developing (including code generation for both pop + swagger)

**Comment by katpavlova** [comment]
I will also need to add developer instructions to emphasize the special sqlite3 tags that are required for using `soda` and compiling sqlite3 into the binary.

**Comment by katpavlova** [comment]
Completed.

**Comment by sh-ura** [comment]
Completed.
